services:
  nginx:
    image: nginx:latest
    container_name: artifactory-nginx
    ports:
      - "80:80"  # external port for web UI and uploads
      - "443:443"
    volumes:
      - ./nginx/artifactory_https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/server.key:/etc/nginx/ssl/server.key
      - ./nginx/server.pem:/etc/nginx/ssl/server.pem

